### ISSUE TITLE
Android mobile app requires "/" at the end of the domain name field to login

### ISSUE THREAD

**Issue by jeydude1** [BIDMCDigitalPsychiatry/LAMP-platform#121]
Hi,

While trying to login to mindLAMP Android app downloaded from Android store, in the domain name field we were just entering the just the host name, example  api.companyname.com/mlpapiservice/v1. We were not able to login to mindLAMP android app, we tried in multiple android phones. 

After looking at the Log file from Android|Files|digital.lamp.minlamp|LampLog.txt from the android phone,  looks like we have to add "/" at the end of the domain name. If we do not add  "/" at the end of the domain name then mindLAMP app hangs or crashes.  But if we add "/" at the end then the application works, able to get into the app and able to go through multiple options like Feed, Prevent etc.

Please let us know if we need to continue doing this? and we are also having issue connecting with Google Fit.

Here is the error log if we do not add "/" at the end of the host name

```
18/2/2021 03:38:06: There was an error signing into Fit. Check the troubleshooting section of the README
for potential issues.
Request code was: 1010
Result code was: 0
18/2/2021 03:39:04: Token : <TOKENInformation>
18/2/2021 03:39:04: Crash : java.lang.IllegalArgumentException: baseUrl must end in /: https://api.companyname.com/mlpapiservice/v1
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:549)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:492)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:53)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:16)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient.getInstance(Unknown Source:2)
at digital.lamp.mindlamp.repository.HomeRepository.<init>(HomeRepository.kt:12)
at digital.lamp.mindlamp.HomeActivity$retrieveCurrentToken$1.onComplete(HomeActivity.kt:408)
at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.1.0:4)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:6)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

18/2/2021 03:39:34: Crash : java.lang.RuntimeException: Unable to start service digital.lamp.mindlamp.repository.LampForegroundService@9b40e27 with null: java.lang.NullPointerException
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4552)
at android.app.ActivityThread.access$2100(ActivityThread.java:274)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException
at digital.lamp.mindlamp.repository.LampForegroundService.onStartCommand(LampForegroundService.kt:70)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4534)
... 8 more

18/2/2021 03:44:40: API Send : 0
18/2/2021 03:44:40: Crash : java.lang.RuntimeException: Unable to start service digital.lamp.mindlamp.repository.LampForegroundService@2b3913f with Intent { cmp=digital.lamp.mindlamp/.repository.LampForegroundService (has extras) }: java.lang.IllegalArgumentException: baseUrl must end in /: https://api.companyname.com/mlpapiservice/v1
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4552)
at android.app.ActivityThread.access$2100(ActivityThread.java:274)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.IllegalArgumentException: baseUrl must end in /: https://api.companyname.com/mlpapiservice/v1
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:549)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:492)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:53)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:16)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient.getInstance(Unknown Source:2)
at digital.lamp.mindlamp.repository.HomeRepository.<init>(HomeRepository.kt:12)
at digital.lamp.mindlamp.sensor.LogUtils.invokeLogData(LogUtils.kt:12)
at digital.lamp.mindlamp.repository.LampForegroundService.collectSensorData(LampForegroundService.kt:207)
at digital.lamp.mindlamp.repository.LampForegroundService.onStartCommand(LampForegroundService.kt:107)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4534)
... 8 more

18/2/2021 03:44:40: Crash : java.lang.IllegalArgumentException: baseUrl must end in /: https://api.companyname.com/mlpapiservice/v1
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:549)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:492)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:53)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:16)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient.getInstance(Unknown Source:2)
at digital.lamp.mindlamp.repository.HomeRepository.<init>(HomeRepository.kt:12)
at digital.lamp.mindlamp.repository.LampForegroundService.invokeAddSensorData(LampForegroundService.kt:234)
at digital.lamp.mindlamp.repository.LampForegroundService.access$invokeAddSensorData(LampForegroundService.kt:40)
at digital.lamp.mindlamp.repository.LampForegroundService$onStartCommand$1.invokeSuspend(LampForegroundService.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

18/2/2021 03:44:40: Crash : java.lang.IllegalArgumentException: baseUrl must end in /: https://api.companyname.com/mlpapiservice/v1
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:549)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:492)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:53)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:16)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient.getInstance(Unknown Source:2)
at digital.lamp.mindlamp.repository.HomeRepository.<init>(HomeRepository.kt:12)
at digital.lamp.mindlamp.repository.LampForegroundService.invokeAddSensorData(LampForegroundService.kt:234)
at digital.lamp.mindlamp.repository.LampForegroundService.access$invokeAddSensorData(LampForegroundService.kt:40)
at digital.lamp.mindlamp.repository.LampForegroundService$onStartCommand$1.invokeSuspend(LampForegroundService.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

18/2/2021 03:49:40: Crash : java.lang.RuntimeException: Unable to start service digital.lamp.mindlamp.repository.LampForegroundService@76dbb2d with Intent { cmp=digital.lamp.mindlamp/.repository.LampForegroundService (has extras) }: java.lang.IllegalArgumentException: baseUrl must end in /: https://api.companyname.com/mlpapiservice/v1
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4552)
at android.app.ActivityThread.access$2100(ActivityThread.java:274)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.IllegalArgumentException: baseUrl must end in /: https://api.companyname.com/mlpapiservice/v1
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:549)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:492)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:53)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:16)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient.getInstance(Unknown Source:2)
at digital.lamp.mindlamp.repository.HomeRepository.<init>(HomeRepository.kt:12)
at digital.lamp.mindlamp.sensor.LogUtils.invokeLogData(LogUtils.kt:12)
at digital.lamp.mindlamp.repository.LampForegroundService.collectSensorData(LampForegroundService.kt:207)
at digital.lamp.mindlamp.repository.LampForegroundService.onStartCommand(LampForegroundService.kt:76)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4534)
... 8 more

Caused by: java.lang.IllegalArgumentException: baseUrl must end in /: https://api.companyname.com/mlpapiservice/v1
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:549)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:492)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:53)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient$instance$2.invoke(RetrofitClient.kt:16)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at digital.lamp.mindlamp.network.retrofit.RetrofitClient.getInstance(Unknown Source:2)
at digital.lamp.mindlamp.repository.HomeRepository.<init>(HomeRepository.kt:12)
at digital.lamp.mi 
```

**Comment by avaidyam** [comment]
@jeydude1 Is this specifically for Galaxy S9 devices or have you observed this behavior across other devices?

**Comment by jeydude1** [comment]
We tried with Samsung Galaxy S9, Note 9, HTC Desire 530 and Moto  android phones. Let us know if you need anything else. 

![DJ_Note9_9F3DC420](https://user-images.githubusercontent.com/205644/108533505-aabf6000-729e-11eb-9b1f-9acf1c71fd08.PNG)
![Screenshot_20210218-091943_Market Feedback Agent](https://user-images.githubusercontent.com/205644/108533518-b01caa80-729e-11eb-90c0-53c56c96c56d.jpg)
![Screenshot_20210218-092003_Market Feedback Agent](https://user-images.githubusercontent.com/205644/108533521-b01caa80-729e-11eb-84c2-58a339f3a68b.jpg)
![Screenshot_20210218-092017_Market Feedback Agent](https://user-images.githubusercontent.com/205644/108533522-b0b54100-729e-11eb-9d9c-660113a1fa9a.jpg)
![Screenshot_20210218-092028_Market Feedback Agent](https://user-images.githubusercontent.com/205644/108533524-b0b54100-729e-11eb-9d3a-078b1fcd6953.jpg)

**Comment by avaidyam** [comment]
@jeydude1 This is fantastic and very helpful information for our development team! Thank you!

**Comment by amaljofyzco** [comment]
Hei Jey,

Could you send me the credentials, When i checked, not getting the issue.

![WhatsApp Image 2021-02-23 at 14 29 34](https://user-images.githubusercontent.com/63775438/108821511-b5059500-75e3-11eb-9468-1d612e5182e5.jpeg)

**Comment by jeydude1** [comment]
@amaljofyzco, Can you share your email, so I can share with you privately. Thanks!

**Comment by amaljofyzco** [comment]
Done:)

**Comment by avaidyam** [comment]
@amaljofyzco Could you share the PR link here that incorporates the change as well as share when the beta build will be available (via the CI/CD)?

**Comment by jeydude1** [comment]
@amaljofyzco, I have shared the test login credentials to your email, please check. Thanks!

**Comment by amaljofyzco** [comment]
Hei JeyDude,

Fixed, this tested with the credentials that you shared in my private mail. Hope you can test in the new update.

Thanks
Amal

**Comment by jeydude1** [comment]
@amaljofyzco Thanks for fixing it, waiting to see new update, once you have the new release in beta/android store, please let me know. We wanted to go live soon. Thanks for you and your team hard work and fixing all the issues immediately!!!

**Comment by jeydude** [comment]
This issue is fixed in the latest beta version of Android app. Thanks for fixing it.
