### ISSUE TITLE
LAMP Docs Update Failures due to Outdated Node.js Version 

### ISSUE THREAD

**Issue by MattMatt27** [BIDMCDigitalPsychiatry/LAMP-platform#826]
**Describe the bug**
I just tried making a very minor change to LAMP-platform (fix the favicon path) but the gh-release build failed and I am wondering if this is a more serious concern that requires addressing. It looks like a few of the packages are now expecting a Node.js version of 18 and we are still using 16. See build error below.
```
Run npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'cheerio@1.0.0',
npm WARN EBADENGINE   required: { node: '>=18.17' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'undici@6.19.8',
npm WARN EBADENGINE   required: { node: '>=18.17' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'whatwg-mimetype@4.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'whatwg-encoding@3.1.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
...
Error:  Unable to build website for locale en.
Error:  ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/home/runner/work/LAMP-platform/LAMP-platform/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/runner/work/LAMP-platform/LAMP-platform/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Error: Process completed with exit code 1.
```

**To Reproduce**
1. Make a change in LAMP-platform package.json
2. Commit changes
3. gh-release should fail

**Expected behavior**
gh-release should succeed and changes should be reflected in the documentation

**Desktop (please complete the following information):**
 - GitHub issue, all devices and OS affected

**Additional context**
Based on my understanding it seems like the two potential solutions are upgrading our Node.js version to 18. Or adding package specific version dependencies for all failing packages so that they continue to work on Node 16.

**Comment by ZCOEngineer** [comment]
We shall review this @MattMatt27

**Comment by sarithapillai8** [comment]
This needs to be done across all repositories, including LAMP-server, LAMP-js, LAMP-worker, LAMP-dashboard, and LAMP-activities (for all activities). It will be a time-consuming process, and we need to thoroughly test each functionality after making the changes. We shall look into this.

**Comment by michaelmenon** [comment]
@kijote0 sure we will start on this on a priority.

**Comment by sarithapillai8** [comment]
@MattMatt27 There are some other errors with the build. Could you please let us know if we need to fix that or will you check it ?

**Comment by MattMatt27** [comment]
@sarithapillai8 If you are able to fix this, it would be greatly appreciated! I did a quick investigation to see if I could figure out why that might be failing but had no luck. The `LAMP-platform/docs/08-develop/12-Training Modules/01-training-modules.md` file has not been updated in a year so I am surprised that it would be running into problems.

**Comment by sarithapillai8** [comment]
Ok we can check on that @MattMatt27

**Comment by MattMatt27** [comment]
@sarithapillai8 Unfortunately it looks like the docs are no longer working after this update. I get the following when I go to [https://docs.lamp.digital/](https://docs.lamp.digital/)

<img width="948" alt="Screenshot 2024-10-29 at 10 45 20 AM" src="https://github.com/user-attachments/assets/ca0bb879-0353-453a-812b-bda6a2788395">

**Comment by sarithapillai8** [comment]
We need some time to fix this issue. I tried reverting, but that brought back the original issue we started. I'll work to resolve this as soon as possible.

**Comment by sarithapillai8** [comment]
@MattMatt27 I’ve been working to resolve the issues by creating code from scratch, updating to the latest versions of React and Docusaurus, and copying the documentation files. I've managed to fix many issues, and I can now see the build files on my local system. The site loads with some errors related to the OpenAPI documentation, though I can still navigate between pages after closing the error pop-up.

I'm currently stuck on an issue: "TypeError: The 'from' argument must be of type string. Received undefined." When debugging, I identified that this error might be caused by the openapi.yml file (potentially due to version changes) or by files generated inside the docusaurus-plugin-openapi/api directory. The undefined schema error may also be related to syntax like this in openapi.tml file:

```
schema:
  "$ref": "#/components/schemas/Activity"
```

I'm uncertain which reference is causing the issue. Could you take a look and help troubleshoot? Please see the working screenshots below.

![image](https://github.com/user-attachments/assets/b1d77ab4-9342-4d70-95c7-444a5b7c0db5)

![image](https://github.com/user-attachments/assets/5ece321c-c421-4cf7-a005-da34b9a9efde)

**Comment by sarithapillai8** [comment]
@kijote0 API docs removed and updated. https://docs.lamp.digital - This site is now loading except the API section. We can continue on this to fix that issue.

**Comment by sarithapillai8** [comment]
@kijote0 Could you please let me know if you've incorporated the latest changes I made before updating?

**Comment by sarithapillai8** [comment]
@kijote0 Updated the build issue. Please have a look.
